// To disable error from Unreal Engine.

#pragma once

#ifndef THIRD_PARTY_INCLUDES_START
#define THIRD_PARTY_INCLUDES_START
#define THIRD_PARTY_INCLUDES_START_TEMP111
#endif // !THIRD_PARTY_INCLUDES_START

#ifndef THIRD_PARTY_INCLUDES_END
#define THIRD_PARTY_INCLUDES_END
#define THIRD_PARTY_INCLUDES_END_TEMP111
#endif // !THIRD_PARTY_INCLUDES_END

THIRD_PARTY_INCLUDES_START
#include "../msquic/msquic.h"
THIRD_PARTY_INCLUDES_END

#ifdef THIRD_PARTY_INCLUDES_START_TEMP111
#undef THIRD_PARTY_INCLUDES_START_TEMP111
#undef THIRD_PARTY_INCLUDES_START
#endif // THIRD_PARTY_INCLUDES_START_TEMP111

#ifdef THIRD_PARTY_INCLUDES_END_TEMP111
#undef THIRD_PARTY_INCLUDES_END_TEMP111
#undef THIRD_PARTY_INCLUDES_END
#endif // THIRD_PARTY_INCLUDES_END_TEMP111
